"""
Django settings for quilombo project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.utils.translation import gettext_lazy as _

from .version import VERSION

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
APP_VERSION = VERSION
INVENTORY_FRESHNESS_DAYS = int(os.environ.get("INVENTORY_FRESHNESS_DAYS", "90"))
MCP_MAX_MUTATION_COLLECTION_ITEMS = int(os.environ.get("MCP_MAX_MUTATION_COLLECTION_ITEMS", "100"))
MCP_MAX_MUTATION_PAYLOAD_BYTES = int(
    os.environ.get("MCP_MAX_MUTATION_PAYLOAD_BYTES", str(256 * 1024))
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-development-only")

# SECURITY WARNING: don't run with debug turned on in production!
IS_PROD = os.environ.get("IS_PROD") == "1"

# Deployment tier. "staging" runs online behind HTTPS with production-like
# hardening, but keeps development-style auth and email so it can be exercised
# without real OAuth accounts or a mail provider.
APP_ENV = os.environ.get("APP_ENV", "production" if IS_PROD else "development")
IS_STAGING = APP_ENV == "staging"
SERVE_SECURE = IS_PROD or IS_STAGING
DEBUG = APP_ENV == "development"
PUBLIC_BASE_URL = os.environ.get(
    "PUBLIC_BASE_URL",
    "https://quilombo.life" if IS_PROD else "http://localhost:8000",
).rstrip("/")
LEGACY_PUBLIC_HOSTS = ("quilombo-v1-mgaitan.onrender.com",)
if IS_PROD and PUBLIC_BASE_URL == "https://quilombo-v1-mgaitan.onrender.com":
    PUBLIC_BASE_URL = "https://quilombo.life"
BOOK_CATALOG_USER_AGENT = os.environ.get(
    "BOOK_CATALOG_USER_AGENT",
    f"Quilombo/{APP_VERSION} (https://github.com/mgaitan/quilombo)",
)
BOOK_CATALOG_TIMEOUT_SECONDS = float(os.environ.get("BOOK_CATALOG_TIMEOUT_SECONDS", "5"))
BOOK_CATALOG_MAX_RETRIES = int(os.environ.get("BOOK_CATALOG_MAX_RETRIES", "2"))

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "ALLOWED_HOSTS",
        ".localhost,127.0.0.1,[::1],quilombo.life,www.quilombo.life,quilombo-v1-mgaitan.onrender.com",
    ).split(",")
    if host.strip()
]
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
MCP_ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "MCP_ALLOWED_HOSTS",
        "localhost:*,127.0.0.1:*,testserver,quilombo.life,www.quilombo.life,quilombo-v1-mgaitan.onrender.com",
    ).split(",")
    if host.strip()
]
MCP_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get(
        "MCP_ALLOWED_ORIGINS",
        "http://localhost:*,http://127.0.0.1:*,https://quilombo.life,https://www.quilombo.life,https://quilombo-v1-mgaitan.onrender.com",
    ).split(",")
    if origin.strip()
]
if IS_PROD:
    for host in ("quilombo.life", "www.quilombo.life", *LEGACY_PUBLIC_HOSTS):
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)
        if host not in MCP_ALLOWED_HOSTS:
            MCP_ALLOWED_HOSTS.append(host)
    for origin in (
        "https://quilombo.life",
        "https://www.quilombo.life",
        "https://quilombo-v1-mgaitan.onrender.com",
    ):
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)
        if origin not in MCP_ALLOWED_ORIGINS:
            MCP_ALLOWED_ORIGINS.append(origin)

# Render injects the service's own hostname; trust it so any Render deploy
# (production or staging) is reachable without hand-maintaining every list.
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if RENDER_EXTERNAL_HOSTNAME:
    render_origin = f"https://{RENDER_EXTERNAL_HOSTNAME}"
    for host_list in (ALLOWED_HOSTS, MCP_ALLOWED_HOSTS):
        if RENDER_EXTERNAL_HOSTNAME not in host_list:
            host_list.append(RENDER_EXTERNAL_HOSTNAME)
    for origin_list in (CSRF_TRUSTED_ORIGINS, MCP_ALLOWED_ORIGINS):
        if render_origin not in origin_list:
            origin_list.append(render_origin)
    if not os.environ.get("PUBLIC_BASE_URL"):
        PUBLIC_BASE_URL = render_origin


# Application definition

INSTALLED_APPS = [
    "inventory.admin_config.QuilomboAdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "anymail",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.socialaccount.providers.google",
    "rest_framework",
    "inventory",
    "drf_spectacular",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "quilombo.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "inventory" / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "quilombo.context_processors.runtime",
                "quilombo.context_processors.social_auth",
            ],
        },
    },
]

WSGI_APPLICATION = "quilombo.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
        disable_server_side_cursors=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "es"

LANGUAGES = [
    ("es", _("Spanish")),
    ("en", _("English")),
]

LOCALE_PATHS = [BASE_DIR / "locale"]

TIME_ZONE = "America/Argentina/Cordoba"

USE_I18N = True

USE_TZ = True

STORAGES = {
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
LOGIN_REDIRECT_URL = "/app/"
LOGOUT_REDIRECT_URL = "/"

DEFAULT_FROM_EMAIL = "Quilombo <no-reply@quilombo.life>"
RESEND_API_KEY = os.environ.get("RESEND_API_KEY", "")
if IS_PROD and RESEND_API_KEY:
    EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"
    ANYMAIL = {"RESEND_API_KEY": RESEND_API_KEY}
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]


def _social_app(client_id_name, secret_name):
    client_id = os.environ.get(client_id_name, "")
    secret = os.environ.get(secret_name, "")
    if not client_id or not secret:
        return []
    return [{"client_id": client_id, "secret": secret, "key": ""}]


SOCIALACCOUNT_ADAPTER = "inventory.accounts.QuilomboSocialAccountAdapter"
ACCOUNT_ADAPTER = "inventory.accounts.QuilomboAccountAdapter"
ACCOUNT_SIGNUP_FIELDS = ["username*", "email*", "password1*", "password2*"]
ACCOUNT_LOGIN_METHODS = {"username", "email"}
# Staging has no mail provider, so it cannot require email verification; every
# other tier (production and local development) keeps it mandatory.
ACCOUNT_EMAIL_VERIFICATION = "optional" if IS_STAGING else "mandatory"
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_LOGIN_ON_GET = False
SOCIALACCOUNT_STORE_TOKENS = False
SOCIALACCOUNT_PROVIDERS = {
    "github": {
        "APPS": _social_app("GITHUB_OAUTH_CLIENT_ID", "GITHUB_OAUTH_CLIENT_SECRET"),
        "SCOPE": ["user:email"],
    },
    "google": {
        "APPS": _social_app("GOOGLE_OAUTH_CLIENT_ID", "GOOGLE_OAUTH_CLIENT_SECRET"),
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        "OAUTH_PKCE_ENABLED": True,
    },
}

if SERVE_SECURE:
    STORAGES["staticfiles"]["BACKEND"] = "whitenoise.storage.CompressedManifestStaticFilesStorage"
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "inventory.authentication.ApiTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "URL_FORMAT_OVERRIDE": None,
    "DEFAULT_PAGINATION_CLASS": "inventory.pagination.InventoryPagination",
    "PAGE_SIZE": 50,
    "DEFAULT_THROTTLE_RATES": {
        "public-search": os.environ.get("PUBLIC_SEARCH_THROTTLE_RATE", "60/min"),
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Quilombo API",
    "DESCRIPTION": "Manage the Quilombo at your workshop",
    "VERSION": APP_VERSION,
    "SERVE_INCLUDE_SCHEMA": False,
}
