
services:
  - type: web
    plan: free
    name: quilombo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn quilombo.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: IS_PROD
        value: 1