# Generated by Django 6.0.8 on 2026-08-14 16:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(blank=True, max_length=64)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='inventory.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], default='member', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='workspaces', through='inventory.Membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='inventory.workspace'),
        ),
        migrations.CreateModel(
            name='LocationRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relation', models.CharField(choices=[('left_of', 'Left of'), ('right_of', 'Right of'), ('above', 'Above'), ('below', 'Below'), ('near', 'Near')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='inventory.location')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='inventory.location')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_relations', to='inventory.workspace')),
            ],
            options={
                'ordering': ['subject__name', 'relation', 'object__name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.workspace'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('tracking_mode', models.CharField(choices=[('bulk', 'Bulk quantity'), ('discrete', 'Discrete count')], default='bulk', max_length=12)),
                ('unit', models.CharField(default='unit', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.workspace')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('bulk_upsert', 'Bulk upsert'), ('adjustment', 'Adjustment'), ('move', 'Move')], max_length=20)),
                ('client_actor', models.CharField(blank=True, max_length=160)),
                ('idempotency_key', models.CharField(blank=True, max_length=160)),
                ('source_kind', models.CharField(choices=[('manual', 'Manual'), ('photo', 'Photo'), ('video', 'Video'), ('import', 'Import'), ('agent', 'Agent'), ('other', 'Other')], default='manual', max_length=16)),
                ('source_reference', models.TextField(blank=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_events', to='inventory.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=20)),
                ('approximate', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='inventory.item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='inventory.location')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='inventory.workspace')),
            ],
            options={
                'ordering': ['item__name', 'location__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='unique_membership'),
        ),
        migrations.AddConstraint(
            model_name='locationrelation',
            constraint=models.UniqueConstraint(fields=('workspace', 'subject', 'relation', 'object'), name='unique_location_relation'),
        ),
        migrations.AddConstraint(
            model_name='locationrelation',
            constraint=models.CheckConstraint(condition=models.Q(('subject', models.F('object')), _negated=True), name='relation_locations_differ'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='unique_location_key'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('workspace', 'key'), name='unique_item_key'),
        ),
        migrations.AddConstraint(
            model_name='inventoryevent',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('workspace', 'idempotency_key'), name='unique_event_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.UniqueConstraint(fields=('workspace', 'item', 'location'), name='unique_holding'),
        ),
        migrations.AddConstraint(
            model_name='holding',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='holding_nonnegative'),
        ),
    ]
