# Generated by Django 6.0.8 on 2026-08-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryevent',
            name='request_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
