# Generated by Django 6.0.8 on 2026-08-15 00:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_apitoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthClient',
            fields=[
                ('client_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('metadata', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.TextField(blank=True)),
                ('scopes', models.JSONField(default=list)),
                ('code_challenge', models.CharField(max_length=160)),
                ('redirect_uri', models.URLField(max_length=1000)),
                ('redirect_uri_provided_explicitly', models.BooleanField(default=True)),
                ('resource', models.URLField(blank=True, max_length=1000)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.oauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthAuthorizationGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_prefix', models.CharField(max_length=12, unique=True)),
                ('code_hash', models.CharField(max_length=64)),
                ('scopes', models.JSONField(default=list)),
                ('code_challenge', models.CharField(max_length=160)),
                ('redirect_uri', models.URLField(max_length=1000)),
                ('redirect_uri_provided_explicitly', models.BooleanField(default=True)),
                ('resource', models.URLField(blank=True, max_length=1000)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.workspace')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.oauthclient')),
            ],
        ),
        migrations.CreateModel(
            name='OAuthCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('access', 'Access token'), ('refresh', 'Refresh token')], max_length=12)),
                ('prefix', models.CharField(max_length=12, unique=True)),
                ('token_hash', models.CharField(max_length=64)),
                ('family_id', models.UUIDField(default=uuid.uuid4)),
                ('scopes', models.JSONField(default=list)),
                ('resource', models.URLField(blank=True, max_length=1000)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.oauthclient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['kind', 'prefix'], name='inventory_o_kind_35f4d6_idx')],
            },
        ),
    ]
