# Generated by Django 6.0.8 on 2026-08-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_backfill_home_workspaces"),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='minimum_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='target_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__isnull', True), ('minimum_quantity__gte', 0), _connector='OR'), name='item_minimum_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('target_quantity__isnull', True), ('target_quantity__gte', 0), _connector='OR'), name='item_target_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__isnull', True), ('target_quantity__isnull', True), ('target_quantity__gte', models.F('minimum_quantity')), _connector='OR'), name='item_target_reaches_minimum'),
        ),
    ]
