# Generated by Django 6.0.8 on 2026-08-22 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_minimum_quantity_item_target_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryevent',
            name='kind',
            field=models.CharField(choices=[('bulk_upsert', 'Bulk upsert'), ('adjustment', 'Adjustment'), ('move', 'Move'), ('item_update', 'Item update'), ('item_delete', 'Item delete')], max_length=20),
        ),
    ]
