# Generated by Django 6.0.8 on 2026-08-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventoryevent_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='apitoken',
            name='can_write',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='can_write',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oauthauthorizationgrant',
            name='can_write',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oauthcredential',
            name='can_write',
            field=models.BooleanField(default=True),
        ),
    ]
