# Generated by Django 6.0.8 on 2026-08-22 23:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_apitoken_can_write_membership_can_write_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='last_observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='last_observed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observed_holdings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holding',
            name='verification_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('unknown', 'Unknown')], default='unknown', max_length=12),
        ),
        migrations.AddField(
            model_name='location',
            name='last_observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='last_observed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observed_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='verification_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('unknown', 'Unknown')], default='unknown', max_length=12),
        ),
        migrations.AlterField(
            model_name='inventoryevent',
            name='kind',
            field=models.CharField(choices=[('bulk_upsert', 'Bulk upsert'), ('adjustment', 'Adjustment'), ('move', 'Move'), ('item_update', 'Item update'), ('item_delete', 'Item delete'), ('audit', 'Audit')], max_length=20),
        ),
    ]
