# Generated by Django 6.0.8 on 2026-08-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_holding_last_observed_at_holding_last_observed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryevent',
            name='undo_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='inventoryevent',
            name='kind',
            field=models.CharField(choices=[('bulk_upsert', 'Bulk upsert'), ('adjustment', 'Adjustment'), ('move', 'Move'), ('item_update', 'Item update'), ('item_delete', 'Item delete'), ('audit', 'Audit'), ('undo', 'Undo')], max_length=20),
        ),
    ]
