# Generated by Django 6.0.8 on 2026-08-30 01:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_normalize_book_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryevent',
            name='kind',
            field=models.CharField(choices=[('bulk_upsert', 'Bulk upsert'), ('adjustment', 'Adjustment'), ('move', 'Move'), ('item_update', 'Item update'), ('item_delete', 'Item delete'), ('label_assertion', 'Label assertion'), ('audit', 'Audit'), ('undo', 'Undo')], max_length=20),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('normalized_key', models.CharField(editable=False, max_length=400)),
                ('search_key', models.CharField(db_index=True, editable=False, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='inventory.workspace')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_value', models.CharField(max_length=200)),
                ('source', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('import', 'Import'), ('confirmation', 'Confirmation')], max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('source_reference', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_label_assertions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_assertions', to='inventory.item')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_labels', to='inventory.workspace')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_assertions', to='inventory.label')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LabelAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
                ('normalized_key', models.CharField(editable=False, max_length=400)),
                ('search_key', models.CharField(db_index=True, editable=False, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='inventory.label')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_aliases', to='inventory.workspace')),
            ],
            options={
                'ordering': ['value', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='label',
            constraint=models.UniqueConstraint(fields=('workspace', 'normalized_key'), name='unique_workspace_label_key'),
        ),
        migrations.AddConstraint(
            model_name='itemlabel',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__isnull', True), models.Q(('confidence__gte', 0), ('confidence__lte', 1)), _connector='OR'), name='item_label_confidence_range'),
        ),
        migrations.AddConstraint(
            model_name='labelalias',
            constraint=models.UniqueConstraint(fields=('workspace', 'normalized_key'), name='unique_workspace_label_alias_key'),
        ),
    ]
