# Generated by Django 6.0.8 on 2026-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_inventoryevent_kind_label_itemlabel_labelalias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryevent',
            name='activity',
            field=models.CharField(choices=[('unspecified', 'Unspecified'), ('observation', 'Observation'), ('purchase', 'Purchase')], default='unspecified', max_length=16),
        ),
    ]
