# Generated by Django 6.0.8 on 2026-09-03 13:00

import django.db.models.deletion
import inventory.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_alter_inventoryevent_kind_label_itemlabel_labelalias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSearchLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('secret', models.CharField(default=inventory.models._new_link_secret, max_length=64, unique=True)),
                ('include_descendants', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_search_links', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_search_links', to='inventory.location')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_search_links', to='inventory.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
